//
//  ReichStarStyleKit.h
//  EICapp
//
//  Created by Julien Bloit on 29/06/2021.
//  Copyright © 2021 jbloit. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, ReichStarStyleKitResizingBehavior)
{
    ReichStarStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    ReichStarStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    ReichStarStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    ReichStarStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect ReichStarStyleKitResizingBehaviorApply(ReichStarStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface ReichStarStyleKit : NSObject

// Drawing Methods
+ (void)drawReichStarWithAngle: (CGFloat)angle hiliteFixedBranch: (CGFloat)hiliteFixedBranch hilitePhasingBranch: (CGFloat)hilitePhasingBranch baseAlpha: (CGFloat)baseAlpha;
+ (void)drawReichStarWithFrame: (CGRect)targetFrame resizing: (ReichStarStyleKitResizingBehavior)resizing angle: (CGFloat)angle hiliteFixedBranch: (CGFloat)hiliteFixedBranch hilitePhasingBranch: (CGFloat)hilitePhasingBranch baseAlpha: (CGFloat)baseAlpha;

@end
